framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
          delivery_orders:
                dsn: '%env(MESSENGER_DELIVERY_ORDER_TRANSPORT_DSN)%'
          delivery_order_status:
              dsn: '%env(MESSENGER_DELIVERY_ORDER_STATUS_TRANSPORT_DSN)%'
          delivery_update_order_status_order:
              dsn: '%env(MESSENGER_DELIVERY_UPDATE_ORDER_STATUS_ORDER_TRANSPORT_DSN)%'
          delivery_update_order_status_kitchen:
              dsn: '%env(MESSENGER_DELIVERY_UPDATE_ORDER_STATUS_KITCHEN_TRANSPORT_DSN)%'
          delivery_users:
              dsn: '%env(MESSENGER_DELIVERY_USERS_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            App\Message\OrderMessage: delivery_orders
            App\Message\OrderStatusMessage: delivery_order_status
            App\Message\UpdateDeliveryStatusMessage: [delivery_update_order_status_order, delivery_update_order_status_kitchen]
            App\Message\UserMessage: delivery_users

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
